Add a Min/Max/Mean test.
Without the fix introduced earlier, this test would result in the
following deadlock.

```
=== RUN   TestMax
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200c2000, 0x53bb87, 0x7, 0x543e28, 0x467c01)
	/home/seanc/src/Go/go19/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200c2000)
	/home/seanc/src/Go/go19/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200c2000, 0xc420037de0)
	/home/seanc/src/Go/go19/src/testing/testing.go:746 +0xd0
testing.runTests(0xc42000a080, 0x5eb720, 0xa, 0xa, 0x0)
	/home/seanc/src/Go/go19/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420037f18, 0xc420037f70)
	/home/seanc/src/Go/go19/src/testing/testing.go:921 +0x111
main.main()
	github.com/circonus-labs/circonusllhist/_test/_testmain.go:74 +0xdb

goroutine 5 [semacquire]:
sync.runtime_SemacquireMutex(0xc4200cf824, 0x0)
	/home/seanc/src/Go/go19/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc4200cf820)
	/home/seanc/src/Go/go19/src/sync/mutex.go:134 +0xee
github.com/circonus-labs/circonusllhist.(*Histogram).ApproxQuantile(0xc4200ce000, 0xc420029ed8, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/seanc/go/src/github.com/circonus-labs/circonusllhist/circonusllhist.go:518 +0x87c
github.com/circonus-labs/circonusllhist.(*Histogram).ValueAtQuantile(0xc4200ce000, 0x3ff0000000000000, 0x0)
	/home/seanc/go/src/github.com/circonus-labs/circonusllhist/circonusllhist.go:591 +0x74
github.com/circonus-labs/circonusllhist.(*Histogram).Max(0xc4200ce000, 0x412e847e00000000)
	/home/seanc/go/src/github.com/circonus-labs/circonusllhist/circonusllhist.go:285 +0x39
github.com/circonus-labs/circonusllhist_test.TestMax(0xc4200c20f0)
	/home/seanc/go/src/github.com/circonus-labs/circonusllhist/circonusllhist_test.go:258 +0x162
testing.tRunner(0xc4200c20f0, 0x543e28)
	/home/seanc/src/Go/go19/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/home/seanc/src/Go/go19/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/circonus-labs/circonusllhist	0.150s
```